import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./componets/Navbar";
import Providers from "@/redux/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-indigo-500 from-10% via-sky-500 via-30% to-emerald-500 to-90%">
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
